/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.spotify;

import java.io.File;
import javax.swing.JFileChooser;

/**
 *
 * @author pchin
 */
public class Home extends javax.swing.JPanel {
    
    
    /**
     * Creates new form Home
     */
    public Home() {
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        direccionTxt = new javax.swing.JTextField();
        seleccionarButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(51, 51, 51));

        direccionTxt.setEditable(false);
        direccionTxt.setFont(new java.awt.Font("Gontserrat", 0, 12)); // NOI18N
        direccionTxt.setForeground(new java.awt.Color(153, 153, 153));
        direccionTxt.setText("Selecciona tu carpeta con musica");
        direccionTxt.setDoubleBuffered(true);
        direccionTxt.setEnabled(false);

        seleccionarButton.setBackground(new java.awt.Color(51, 51, 51));
        seleccionarButton.setFont(new java.awt.Font("Gontserrat", 0, 12)); // NOI18N
        seleccionarButton.setForeground(new java.awt.Color(0, 255, 0));
        seleccionarButton.setText("Seleccionar");
        seleccionarButton.setToolTipText("Selecciona la carpeta con la musica a importar");
        seleccionarButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                seleccionarButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(direccionTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(seleccionarButton)
                .addContainerGap(191, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(direccionTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(seleccionarButton))
                .addContainerGap(332, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void seleccionarButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_seleccionarButtonMouseClicked
        
        JFileChooser selArchivo = new JFileChooser();
        
        selArchivo.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        
        int resultado = selArchivo.showOpenDialog(null);
        
        if(resultado == JFileChooser.APPROVE_OPTION){
            
            File carpeta = selArchivo.getSelectedFile();
            
            direccionTxt.setText(carpeta.getAbsolutePath());
            
        }
        
    }//GEN-LAST:event_seleccionarButtonMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField direccionTxt;
    private javax.swing.JButton seleccionarButton;
    // End of variables declaration//GEN-END:variables
}
