/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.spotify;


import java.io.File;
import javax.swing.JFileChooser;
import com.estructuras.ArbolBinario;
import com.estructuras.Cancion;
import com.estructuras.ListaDobleEnlazadaCircular;
import com.utilidades.Reproductor;
import java.awt.Component;
import javax.swing.DefaultListCellRenderer;
import javax.swing.DefaultListModel;
import javax.swing.JList;
import javax.swing.JOptionPane;



/**
 *
 * @author pchin
 */
public class Inicio extends javax.swing.JFrame {
    
    DefaultListModel<Cancion> modeloLista = new DefaultListModel<>();
    Reproductor reproductor = new Reproductor();
    
    ListaDobleEnlazadaCircular lista = new ListaDobleEnlazadaCircular();

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Inicio.class.getName());


    public Inicio() {
        
        initComponents();
        listadoCanciones.setModel(modeloLista);
        
        listadoCanciones.setCellRenderer(new DefaultListCellRenderer() {
            @Override
            public Component getListCellRendererComponent(JList<?> list, Object value,
                int index, boolean isSelected, boolean cellHasFocus) {

                    super.getListCellRendererComponent(list, value, index, isSelected, cellHasFocus);
                    Cancion c = (Cancion) value;
                    setText(c.nombre + " — " + c.artista +  " (" + c.duracionReal + ")");

                    return this;
                }
        });
        listadoCanciones.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                if (evt.getClickCount() == 2) {
                    Cancion seleccionada = listadoCanciones.getSelectedValue();
                    if (seleccionada != null) {
                        reproductor.detener();
                        reproductor.reproducir(seleccionada, lista); 
                    }
                    else{
                        JOptionPane.showMessageDialog(null, "No has seleccionado ninguna cancion", "ADVERTENCIA", JOptionPane.WARNING_MESSAGE);
                    }
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        spotifyLabel = new javax.swing.JLabel();
        agregarButton = new javax.swing.JButton();
        playlistButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        listadoCanciones = new javax.swing.JList<>();
        txtBuscar = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        playButton = new javax.swing.JButton();
        anteriorButton = new javax.swing.JButton();
        siguienteButton = new javax.swing.JButton();
        arbolTxt = new javax.swing.JLabel();
        listaTxt = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        spotifyLabel.setFont(new java.awt.Font("Gontserrat SemiBold", 0, 24)); // NOI18N
        spotifyLabel.setForeground(new java.awt.Color(0, 255, 51));
        spotifyLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        spotifyLabel.setText("Spotify");
        jPanel1.add(spotifyLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, 1020, -1));

        agregarButton.setFont(new java.awt.Font("Gontserrat", 0, 12)); // NOI18N
        agregarButton.setText("Importar Musica");
        agregarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarButtonActionPerformed(evt);
            }
        });
        jPanel1.add(agregarButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 130, 30));

        playlistButton.setFont(new java.awt.Font("Gontserrat", 0, 12)); // NOI18N
        playlistButton.setText("Playlist");
        playlistButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                playlistButtonMouseClicked(evt);
            }
        });
        jPanel1.add(playlistButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 80, 130, 30));

        listadoCanciones.setBackground(new java.awt.Color(102, 102, 102));
        listadoCanciones.setFont(new java.awt.Font("Gontserrat", 0, 14)); // NOI18N
        listadoCanciones.setForeground(new java.awt.Color(255, 255, 255));
        listadoCanciones.setModel(modeloLista);
        listadoCanciones.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        listadoCanciones.setSelectionForeground(new java.awt.Color(51, 51, 51));
        jScrollPane1.setViewportView(listadoCanciones);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 340, 510));

        txtBuscar.setFont(new java.awt.Font("Gontserrat", 0, 12)); // NOI18N
        jPanel1.add(txtBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 240, -1));

        btnBuscar.setFont(new java.awt.Font("Gontserrat", 0, 12)); // NOI18N
        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        jPanel1.add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 100, 90, -1));

        playButton.setBackground(new java.awt.Color(204, 204, 204));
        playButton.setFont(new java.awt.Font("Gontserrat", 0, 12)); // NOI18N
        playButton.setForeground(new java.awt.Color(0, 0, 0));
        playButton.setText("Play/Pause");
        playButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playButtonActionPerformed(evt);
            }
        });
        jPanel1.add(playButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 660, -1, -1));

        anteriorButton.setBackground(new java.awt.Color(204, 204, 204));
        anteriorButton.setFont(new java.awt.Font("Gontserrat", 0, 12)); // NOI18N
        anteriorButton.setForeground(new java.awt.Color(0, 0, 0));
        anteriorButton.setText("Anterior");
        anteriorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anteriorButtonActionPerformed(evt);
            }
        });
        jPanel1.add(anteriorButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 660, -1, -1));

        siguienteButton.setBackground(new java.awt.Color(204, 204, 204));
        siguienteButton.setFont(new java.awt.Font("Gontserrat", 0, 12)); // NOI18N
        siguienteButton.setForeground(new java.awt.Color(0, 0, 0));
        siguienteButton.setText("Siguiente");
        siguienteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                siguienteButtonActionPerformed(evt);
            }
        });
        jPanel1.add(siguienteButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 660, -1, -1));

        arbolTxt.setText("Arbol: ");
        jPanel1.add(arbolTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, -1));

        listaTxt.setText("Lista:");
        jPanel1.add(listaTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 80, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1321, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1321, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 862, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 862, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void playlistButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_playlistButtonMouseClicked
        
    }//GEN-LAST:event_playlistButtonMouseClicked

    private void agregarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarButtonActionPerformed
        JFileChooser chooser = new JFileChooser();
            chooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
            int resultado = chooser.showOpenDialog(null);
            if (resultado == JFileChooser.APPROVE_OPTION) {
                File carpeta = chooser.getSelectedFile();

                ArbolBinario arbol = ArbolBinario.getInstancia();
                arbol.raiz = null;      //LIMPIAMOS EL ARBOL ANTES DE VOLVER A CARGAR
                lista.limpiarLista();
                lista.contador = 0;
                arbol.cantidad = 0;     // Y LA CANTIDAD TAMBIEN


                
                arbol.cargarCarpeta(carpeta.getAbsolutePath());
                arbol.inOrderAListaDoble(arbol.raiz, lista);

                modeloLista.clear();    // LIMPIAMOS LA LISTA
                arbol.inOrderALista(arbol.raiz, modeloLista);

                arbolTxt.setText("Arbol: " + arbol.cantidad);
                listaTxt.setText("Lista: " + lista.contador); 
                
                JOptionPane.showMessageDialog(this, "Canciones agregadas: " + arbol.cantidad);
            }
    }//GEN-LAST:event_agregarButtonActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
       buscarCancion(txtBuscar.getText());
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void playButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_playButtonActionPerformed
        
        if(reproductor.estaReproduciendo() == true){
            reproductor.pausar();
        }    
        else{
            reproductor.reanudar();
        }
    }//GEN-LAST:event_playButtonActionPerformed

    private void siguienteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_siguienteButtonActionPerformed

        Cancion actual = reproductor.getCancionActual();
        Cancion siguiente = lista.buscarSiguiente(actual.ruta);
        buscarCancion(siguiente.nombre);
        reproductor.siguienteCancion();
    }//GEN-LAST:event_siguienteButtonActionPerformed

    private void anteriorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anteriorButtonActionPerformed
        Cancion actual = reproductor.getCancionActual();
        Cancion anterior = lista.buscarAnterior(actual.ruta);
        buscarCancion(anterior.nombre);
        reproductor.reproducir(anterior.ruta);
    }//GEN-LAST:event_anteriorButtonActionPerformed


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Inicio().setVisible(true));
    }

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agregarButton;
    private javax.swing.JButton anteriorButton;
    private javax.swing.JLabel arbolTxt;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel listaTxt;
    private javax.swing.JList<Cancion> listadoCanciones;
    private javax.swing.JButton playButton;
    private javax.swing.JButton playlistButton;
    private javax.swing.JButton siguienteButton;
    private javax.swing.JLabel spotifyLabel;
    private javax.swing.JTextField txtBuscar;
    // End of variables declaration//GEN-END:variables

    private void buscarCancion(String textoBusqueda) {
        if (textoBusqueda.isEmpty()) {
            return;
        }

        for (int i = 0; i < modeloLista.getSize(); i++) {
            
            Cancion c = modeloLista.getElementAt(i);

            if (c.nombre.toLowerCase().contains(textoBusqueda.toLowerCase()) || c.artista.toLowerCase().contains(textoBusqueda.toLowerCase())) {

                listadoCanciones.setSelectedIndex(i);      //lo selecciona
                listadoCanciones.ensureIndexIsVisible(i);   // desplaza la lista hasta ahi
                return;
            }
        }

        javax.swing.JOptionPane.showMessageDialog(this, "Canción no encontrada", "Búsqueda", javax.swing.JOptionPane.INFORMATION_MESSAGE);
    }

}
